sonar.projectKey=nest-gRPC-mTLS
sonar.projectName=Nest gRPC mTLS App
sonar.projectVersion=1.0

# Sources and Tests
sonar.sources=user-service/src,order-service/src
sonar.tests=user-service/test,order-service/test
sonar.exclusions=**/node_modules/**,**/*.spec.ts

sonar.language=ts
sonar.sourceEncoding=UTF-8

# Optional: Coverage reports (from Jest)
sonar.javascript.lcov.reportPaths=user-service/coverage/lcov.info,order-service/coverage/lcov.info

# ESLint Reports
sonar.javascript.eslint.reportPaths=user-service/eslint-report.json,order-service/eslint-report.json
